let Time = 0
let strip = neopixel.create(DigitalPin.P0, 8, NeoPixelMode.RGB)
strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Green))
strip.show()
basic.forever(function () {
    strip.rotate(1)
    strip.show()
    basic.pause(Time)
    Time = randint(50, 500)
    strip.rotate(1)
    strip.show()
    basic.pause(Time)
    Time = randint(50, 500)
    strip.rotate(1)
    strip.show()
    basic.pause(Time)
    Time = randint(50, 500)
})
